# Generated by Django 4.1.1 on 2022-10-17 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGlobal', '0003_blog_author_alter_blog_body_alter_blog_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tipo',
        ),
    ]
