# Generated by Django 4.1.1 on 2022-10-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGlobal', '0004_remove_blog_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='descripcion',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='blog',
            name='titulo',
            field=models.CharField(max_length=60),
        ),
    ]
